CREATE TABLE vehicles (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    registration VARCHAR(8) UNIQUE NOT NULL,
    make VARCHAR(32) NOT NULL,
    model VARCHAR(32) NOT NULL,
    year SMALLINT NOT NULL,
    fuel_type VARCHAR(15) NOT NULL,
    engine_size_cc INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);